### ISSUE TITLE
Move api key to repository secrets

### ISSUE THREAD

**Issue by oSumAtrIX** [Flow-Launcher/dotnet-template#3]
The deployment key has been leaked in the appveyor configuration file **[dotnet-template/appveyor.yml](https://github.com/Flow-Launcher/dotnet-template/blob/master/appveyor.yml).**
It should be invalidated and the new API key should be put into the repository secrets.

**Comment by jjw24** [comment]
Hey thanks for the note, but that (deployment key) variable is actually an AppVeyor encrypted secure variable not related to GitHub and can only be used for projects belonging to the account, so it's not an API key.

**Comment by oSumAtrIX** [comment]
Thank you.
