### ISSUE TITLE
Update dotnet-template appveyor CICD to GitHub

### ISSUE THREAD

**Issue by jjw24** [Flow-Launcher/dotnet-template#4]
Update dotnet-template appveyor CICD to GitHub actions publishing to GitHub Releases. Current deployment to NuGet is not correct and should not be used.

**Comment by JohnTheGr8** [comment]
Just noticed this one... could you elaborate? What's the problem with the current setup?

**Comment by jjw24** [comment]
lol I don't remember, the latest release looks ok in NuGet so will close this.
