### ISSUE TITLE
Function to filter results

### ISSUE THREAD

**Issue by HorridModz** [Flow-Launcher/dotnet-template#8]
Hi, I don't know where to put this as it's more of a universal API thing than a dotnet thing. But I was wondering if there was a good way to filter results and get matches based on the search query, and if not, if it could be implemented.

For reference, I did write a function for this myself:
```C#
private static List<Result> GetMatchedResults(List<Result> allResults, string searchQuery)
{
	/* Finds all matched results based on the user's query
	 * A result is considered a match if its title is contained in the user's input
	 * For example, using a result with title "add":
	 *   "add" - match
	 *   " add" - match
	 *   "add foo" - match
	 *   "a" - match
	 *   "ad" - match
	 *   ". add" - not a match
	 *   "addx" - not a match
	 *   "adx" - not a match
	 *   
	 *   If the query is empty or whitespace, all results will be considered matches
	*/
	List<Result> results = new List<Result>();
	foreach (Result result in allResults)
	{
		// Add a space to make sure the user has not typed the start of the command but not the command itself
		// For example, `addx` instead of just `add`
		string title = result.Title + " ";
		var zippedTitleAndQuery = title.TrimStart().Zip(searchQuery);
		bool match = true;
		foreach (List<char> chars in zippedTitleAndQuery)
		{
			if (chars[0] != chars[1])
			{
				match = false;
				break;
			}
		}
		if (match) { results.Add(result); }
	}
	return results;
}
```

With the `string.Zip` extension function defined as this:

```C#
static class ZipStringExtension
{
	public static IEnumerable<List<char>> Zip(this string str1, string str2)
	{
		/* Zips two strings together, so that they may be iterated over.
		*  Wrapper for Enumerable.Zip() method; convenient because it converts strings to lists and specifies to return zipped element as an
		*  IEnumerable containing List<char>'s of the two chars for each index
		*  Returns an IEnumerable containing Lists of two chars each.
		*  The function can be called and iterated over like this:
		*  foreach (List<char> chars in Zip(str1, str2)
		 {
			 char char1 = chars[0];         char char2 = chars[1];
		 }
		*/
		return str1.ToList().Zip(str2.ToList(), (char1, char2) => new List<char>() { char1, char2 });
	}
}
```

**Comment by jjw24** [comment]
C# plugins can directly utilise flow's own query matcher mechanism, which I think is what you are after. This also means the way user uses your plugin to search result will be consistent.

Have look at the bookmark plugin, it also does return all results when query is empty like you mentioned.

https://github.com/Flow-Launcher/Flow.Launcher/blob/42939eaba2b8f27832065b7e594d27ab1bfd3921/Plugins/Flow.Launcher.Plugin.BrowserBookmark/Commands/BookmarkLoader.cs#L11

**Comment by HorridModz** [comment]
@jjw24 Sorry, I badly phrased my question. Yes, this is a useful function (good job creating it :) ) - however, it is fuzzy rather than exact, and it doesn't have to start at the beginning to be a match.

This could definitely work, however, from what I can tell my algorithm for matching is different and in my opinion better suited for my purpose. So, I was suggesting to maybe add something non-fuzzy that was similar to what I have created (if I'm not mistaken and that isn't already possible to do).

However, this isn't absolutely necessary, especially with the fuzzy search query matcher. It's just an idea. Go ahead and close the issue if you believe the fuzzy search algorithm is good enough /neu

**Comment by jjw24** [comment]
Although it's fuzzy search but the scenarios you listed are already covered though (do let me know if there is an actual scenario that is not included and I can take another look at the code). It's called fuzzy matcher but it doesn't just do fuzzy matching, if there is a user search scenario that's not included we should add it, otherwise if it's a plugin specific use case it may be better to be implemented by the plugin itself.

**Comment by jjw24** [comment]
Closing this for now, if your scenario is not covered then let's reopen a discuss.
